version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bluepips
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bluepips_dev
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: bluepips-db-data
